### ISSUE TITLE
Some langauge issues that need correcting that I cannot do PRs on

### ISSUE THREAD

**Issue by gesslar** [Delwing/mudlet-docs#2]
EDIT: This issue now only reflects this repo

1. The About section of this repo: https://github.com/Delwing/mudlet-docs

Extracts Mudlet Wiki contents and converts them into .lua files that can be used in a workspace to provide autocomplete, popup docs, and hint parameters.

**Comment by Delwing** [comment]
Thanks. Extension has separate repository: https://github.com/Delwing/mudlet-scripts-sdk

**Comment by gesslar** [comment]
Updated issue

**Comment by Delwing** [comment]
Already corrected. Thanks.
